# Generated by Django 5.0.2 on 2024-03-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printercategory',
            options={'verbose_name_plural': 'Printer Catigories'},
        ),
    ]
